// +build !ignore_autogenerated

/*
Copyright 2018 Datadog Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Birdcage) DeepCopyInto(out *Birdcage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Birdcage.
func (in *Birdcage) DeepCopy() *Birdcage {
	if in == nil {
		return nil
	}
	out := new(Birdcage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Birdcage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdcageList) DeepCopyInto(out *BirdcageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Birdcage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdcageList.
func (in *BirdcageList) DeepCopy() *BirdcageList {
	if in == nil {
		return nil
	}
	out := new(BirdcageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BirdcageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdcageSourceObject) DeepCopyInto(out *BirdcageSourceObject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdcageSourceObject.
func (in *BirdcageSourceObject) DeepCopy() *BirdcageSourceObject {
	if in == nil {
		return nil
	}
	out := new(BirdcageSourceObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdcageSpec) DeepCopyInto(out *BirdcageSpec) {
	*out = *in
	out.SourceObject = in.SourceObject
	in.TargetObject.DeepCopyInto(&out.TargetObject)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdcageSpec.
func (in *BirdcageSpec) DeepCopy() *BirdcageSpec {
	if in == nil {
		return nil
	}
	out := new(BirdcageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdcageStatus) DeepCopyInto(out *BirdcageStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdcageStatus.
func (in *BirdcageStatus) DeepCopy() *BirdcageStatus {
	if in == nil {
		return nil
	}
	out := new(BirdcageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdcageTargetObject) DeepCopyInto(out *BirdcageTargetObject) {
	*out = *in
	in.Patch.DeepCopyInto(&out.Patch)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdcageTargetObject.
func (in *BirdcageTargetObject) DeepCopy() *BirdcageTargetObject {
	if in == nil {
		return nil
	}
	out := new(BirdcageTargetObject)
	in.DeepCopyInto(out)
	return out
}
