apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: birdcages.datadoghq.datadoghq.com
spec:
  group: datadoghq.datadoghq.com
  names:
    kind: Birdcage
    plural: birdcages
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            sourceObject:
              properties:
                name:
                  minLength: 1
                  type: string
                namespace:
                  minLength: 1
                  type: string
              required:
              - name
              - namespace
              type: object
            targetObject:
              properties:
                name:
                  minLength: 1
                  type: string
                namespace:
                  minLength: 1
                  type: string
                patch:
                  type: string
              required:
              - name
              - namespace
              - patch
              type: object
          required:
          - sourceObject
          - targetObject
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
